name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *" # Update once daily (00:00 UTC / 07:00 WIB)
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Profile Summary Cards
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: dicky6ulin
          BRANCH_NAME: main
          UTC_OFFSET: 7
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
